### ISSUE TITLE
No-unreachable-types does not account for directive's parameters

### ISSUE THREAD

**Issue by ilyavolodin** [B2o5T/graphql-eslint#301]
When an enum or type is used as a parameter in a directive `no-unreachable-types` reports that enum/type as unreachable. Repro case:
```graphql
directive @omit(unlessContains: [String], unlessContainsTypes: OmitTypes) on FIELD_DEFINITION

"Types of 'unlessContainsTypes' omit"
enum OmitTypes {
  "Scalar fields"
  scalar
  "Complex type fields"
  nonScalar
}
```

`OmitTypes` will be marked as unreachable by the rule.

On a slightly different note, "unreachable" is very confusing term here. I would've called it "unused" instead. Types are always reachable, but can be unused.

**Comment by dotansimha** [comment]
Fixed on `master`. Will cut a release soon :)

**Comment by dotansimha** [comment]
Fixed in `v1.0.0`! 🎉

**Comment by Yimiprod** [comment]
Still having that issue using the version `^3.12.0` of `@graphql-eslint/eslint-plugin`:

<img width="787" alt="image" src="https://user-images.githubusercontent.com/2227867/216094753-a941c2e9-1c01-4372-848b-a4de87b74fb1.png">

Any idea why ?

**Comment by B2o5T** [comment]
@Yimiprod this is a bug caused by https://github.com/B2o5T/graphql-eslint/pull/1108 fix, will be fixed in next release

**Comment by B2o5T** [comment]
@Yimiprod try `3.16.1-alpha-20230226190709-158a25e`

**Comment by Yimiprod** [comment]
It looks good to me:
<img width="786" alt="image" src="https://user-images.githubusercontent.com/2227867/221618138-a6761ef2-a5fd-4ab6-9ed1-e1478d0ea8dc.png">
